name: Scrape Trending Tickers

on:
  schedule:
    - cron: '*/60 * * * *' # Run every hour at the top of the hour

jobs:

  scrape-tickers:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests beautifulsoup4 jinja2
        
    - name: Scrape Trending Tickers
      run: |
        python scrape_tickers.py
        
    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update trending tickers
        file_pattern: index.html tickers.db
