name: Scrape Trending Tickers

on:
  schedule:
    - cron: '10 * * * *' # Run every hour at the top of the hour

jobs:

  scrape-tickers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: ${{ github.event.before }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests beautifulsoup4 jinja2 lxml datetime feedparser
        
    - name: Scrape Trending Tickers
      run: |
        python scrape_tickers.py
        
    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update trending tickers
        file_pattern: index.html trending_tickers.db
